import { pgTable, text, timestamp, boolean, integer, jsonb, index, uniqueIndex } from 'drizzle-orm/pg-core';
import type { Workspace } from '@/lib/types';
export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('email_verified').notNull().default(false), image: text('image'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() });
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expires_at').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }) });
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: timestamp('access_token_expires_at'), refreshTokenExpiresAt: timestamp('refresh_token_expires_at'), scope: text('scope'), password: text('password'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() });
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at').notNull(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() });
// Aggregate updates are serialized with SELECT FOR UPDATE. Membership remains relational
// and is the authorization boundary; clients never submit replacement workspace state.
export const workspaces = pgTable('workspace', { id: text('id').primaryKey(), name: text('name').notNull(), data: jsonb('data').$type<Workspace>().notNull(), version: integer('version').notNull().default(0), createdAt: timestamp('created_at').notNull().defaultNow() });
export const memberships = pgTable('membership', { id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }), role: text('role').notNull().default('member') }, t => [uniqueIndex('membership_unique').on(t.workspaceId,t.userId),index('membership_user').on(t.userId)]);
export const auditLogs = pgTable('audit_log', { id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id), actorId: text('actor_id').notNull().references(() => user.id), action: text('action').notNull(), entityId: text('entity_id'), detail: jsonb('detail').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() }, t => [index('audit_workspace_time').on(t.workspaceId,t.createdAt)]);
